import { Router } from 'express';
import { getNotifications, markRead, markAllRead, deleteNotification, getUnreadCount } from '../controllers/notifications.controller';
import { authenticate } from '../middleware/auth';
const router = Router();
router.use(authenticate);
router.get('/',             getNotifications);
router.get('/unread-count', getUnreadCount);
router.patch('/:id/read',   markRead);
router.patch('/read-all',   markAllRead);
router.delete('/:id',       deleteNotification);
export default router;
