import { Router } from 'express';
import { getProperties, getProperty, createProperty, updateProperty, deleteProperty, getPropertyStats, addPropertyManager, removePropertyManager, getPropertyUnits, createUnit, updateUnit, getMapProperties, generatePropertySummary } from '../controllers/properties.controller';
import { authenticate, authorize } from '../middleware/auth';
import { UserRole } from '@prisma/client';
const router = Router();
router.use(authenticate);
router.get('/',                 getProperties);
router.get('/map',              getMapProperties);
router.get('/leases/all',       getAllLeases);
router.get('/:id',              getProperty);
router.get('/:id/stats',        getPropertyStats);
router.get('/:id/units',        getPropertyUnits);
router.post('/',                authorize(UserRole.OWNER, UserRole.ADMIN), createProperty);
router.put('/:id',              authorize(UserRole.OWNER, UserRole.MANAGER, UserRole.ADMIN), updateProperty);
router.delete('/:id',           authorize(UserRole.OWNER, UserRole.ADMIN), deleteProperty);
router.post('/:id/managers',    authorize(UserRole.OWNER, UserRole.ADMIN), addPropertyManager);
router.delete('/:id/managers/:managerId', authorize(UserRole.OWNER, UserRole.ADMIN), removePropertyManager);
router.post('/:id/units',       authorize(UserRole.OWNER, UserRole.MANAGER, UserRole.ADMIN), createUnit);
router.put('/:id/units/:unitId',authorize(UserRole.OWNER, UserRole.MANAGER, UserRole.ADMIN), updateUnit);
router.post('/:id/ai-summary',  generatePropertySummary);
export default router;
